apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: detection1
  namespace: serverless
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 60s
    spec:
      containers:
      - image: docker.io/kiemtcb/detection-object:4.7arm@sha256:6b8bd5ddc833054c49f48ce3ae8981bfedb207567fc26033ba4e8ceba796a11c
        ports:
        - containerPort: 8080
      nodeSelector:
        kubernetes.io/hostname: jetson
